name: Notification Sender

on: [push]

jobs:
  notifications:
    runs-on: ubuntu-latest
    steps:
      - name: send discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "{{ EVENT_PAYLOAD.sender.login }} pushed to the {{ EVENT_PAYLOAD.repository.full_name }} repository."
