name: Test Runner

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run tests
        run: pytest
